import Foundation
import Testing
@testable import RiffProtocol

@MainActor struct ChangelogTests {
    private func release(_ version: String = "0.1.0", id: Int64 = 42, updated: String = "2026-09-11") -> GitHubRelease {
        GitHubRelease(tag_name: "companion-v" + version, draft: false, prerelease: false, assets: [
            .init(name: "Riff-\(version)-win-x64.zip", state: "uploaded", size: 100),
            .init(name: "CHANGELOG.md", state: "uploaded", size: 100, id: id, updated_at: updated)
        ])
    }
    @Test func requestsTheReleaseAssetWithoutPCOrGitHubCredentials() throws {
        let request = try ReleaseChangelogClient.request(for: release())
        #expect(request.url?.absoluteString == "https://api.github.com/repos/binbandit/riff/releases/assets/42")
        #expect(request.value(forHTTPHeaderField: "Accept") == "application/octet-stream")
        #expect(request.value(forHTTPHeaderField: "Authorization") == nil)
        var old = release(); old = GitHubRelease(tag_name: old.tag_name, draft: false, prerelease: false, assets: [.init(name: "Riff-0.1.0-win-x64.zip", state: "uploaded", size: 100), .init(name: "changelog.md", state: "uploaded", size: 100)])
        #expect(try ReleaseChangelogClient.request(for: old).url?.absoluteString == "https://github.com/binbandit/riff/releases/download/companion-v0.1.0/changelog.md")
    }
    @Test func assetIdentitySurvivesJSONAndInvalidatesChangedNotes() throws {
        let original = release()
        let decoded = try JSONDecoder().decode(GitHubRelease.self, from: JSONEncoder().encode(original))
        #expect(decoded.changelogAsset?.id == 42)
        #expect(decoded.changelogAsset?.updated_at == "2026-09-11")
        #expect(decoded.changelogKey == original.changelogKey)
        #expect(original.changelogKey != release(id: 43).changelogKey)
        #expect(original.changelogKey != release(updated: "2026-09-12").changelogKey)
        let legacy = try JSONDecoder().decode(GitHubRelease.Asset.self, from: Data(#"{"name":"CHANGELOG.md","state":"uploaded","size":100}"#.utf8))
        #expect(legacy.id == nil && legacy.updated_at == nil)
    }
    @Test func missingWrongAndOversizedAssetsDoNotDownload() {
        let base = release()
        for asset in [GitHubRelease.Asset(name: "../CHANGELOG.md", state: "uploaded", size: 100), .init(name: "CHANGELOG.md", state: "starter", size: 0), .init(name: "CHANGELOG.md", state: "uploaded", size: 2_000_000)] {
            let bad = GitHubRelease(tag_name: base.tag_name, draft: false, prerelease: false, assets: [base.assets[0], asset])
            #expect(throws: (any Error).self) { try ReleaseChangelogClient.request(for: bad) }
        }
    }
    @Test func preservesMarkdownExactlyAndRejectsUnreadableFiles() throws {
        let source = "# Features\n\n- **Bold** and [links](https://github.com)\n\n```swift\nlet x = 1\n```\n\n| A | B |\n| - | - |\n| 1 | 2 |\n"
        #expect(try ReleaseChangelogClient.decode(Data(source.utf8)) == source)
        for data in [Data(), Data([0xFF, 0xFE]), Data("  \n ".utf8), Data(repeating: 65, count: ReleaseChangelogClient.maximumBytes + 1)] {
            #expect(throws: (any Error).self) { try ReleaseChangelogClient.decode(data) }
        }
    }
    @Test func hidesGeneratedAndInlineCommentsButPreservesCodeExamples() {
        let source = "# Changes\n<!-- Generated by git-cliff. Do not edit manually. -->\n### Added\n- New <!-- internal -->sounds\n<!-- multi\nline -->Visible\n```html\n<!-- literal -->\n```\n    <!-- indented code -->\n`<!-- inline code -->`"
        let displayed = MarkdownDisplay.hidingComments(in: source)
        #expect(!displayed.contains("Generated by") && !displayed.contains("internal") && !displayed.contains("line -->"))
        #expect(displayed.contains("- New sounds") && displayed.contains("Visible"))
        #expect(displayed.contains("<!-- literal -->") && displayed.contains("<!-- indented code -->") && displayed.contains("`<!-- inline code -->`"))
    }
    @Test func readsCachedMarkdownAcrossLaunchesAndKeepsItAfterOfflineRefresh() async throws {
        let folder = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: folder) }
        let file = folder.appendingPathComponent("cache.json")
        var calls = 0
        let original = ReleaseChangelogStore(cacheURL: file) { _ in calls += 1; return "# Features\n\n- New sounds" }
        await original.load(release())
        let reopened = ReleaseChangelogStore(cacheURL: file) { _ in calls += 1; throw URLError(.notConnectedToInternet) }
        await reopened.load(release())
        #expect(calls == 1 && reopened.markdown == original.markdown)
        await reopened.load(release(), force: true)
        #expect(calls == 2 && reopened.markdown == original.markdown && reopened.failure != nil)
        await reopened.load(release("0.2.0", id: 43))
        #expect(reopened.markdown == nil && reopened.failure != nil)
    }
    @Test func replacedAssetFetchesFreshContentEvenWithTheSameReleaseTag() async throws {
        let folder = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: folder) }
        var calls = 0
        let store = ReleaseChangelogStore(cacheURL: folder.appendingPathComponent("cache.json")) { _ in calls += 1; return "Version \(calls)" }
        await store.load(release())
        await store.load(release(id: 43))
        #expect(calls == 2 && store.markdown == "Version 2")
    }
    @Test func delayedOlderRequestCannotReplaceTheNewRelease() async throws {
        let folder = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: folder) }
        var resume: CheckedContinuation<String, Never>?
        let store = ReleaseChangelogStore(cacheURL: folder.appendingPathComponent("cache.json")) { release in
            if release.tag_name == "companion-v0.1.0" { return await withCheckedContinuation { resume = $0 } }
            return "# New release"
        }
        let old = Task { await store.load(release()) }
        while resume == nil { await Task.yield() }
        await store.load(release("0.2.0", id: 43))
        resume?.resume(returning: "# Old release")
        await old.value
        #expect(store.markdown == "# New release" && !store.loading && store.failure == nil)
    }
}
